// <auto-generated />
using System;
using DevelopmentTimer.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DevelopmentTimer.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250919133810_SeededUpdatedDataForTaskItems")]
    partial class SeededUpdatedDataForTaskItems
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DevelopmentTimer.DAL.Entities.ExtensionsRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeveloperId")
                        .HasColumnType("int");

                    b.Property<int>("ExtraHours")
                        .HasColumnType("int");

                    b.Property<string>("Justification")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("TaskItemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeveloperId");

                    b.HasIndex("TaskItemId");

                    b.ToTable("ExtensionRequests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeveloperId = 2,
                            ExtraHours = 1,
                            Justification = "To create responsive design",
                            TaskItemId = 1
                        },
                        new
                        {
                            Id = 2,
                            DeveloperId = 3,
                            ExtraHours = 2,
                            Justification = "To create responsive design",
                            TaskItemId = 3
                        });
                });

            modelBuilder.Entity("DevelopmentTimer.DAL.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MaxHoursPerDay")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MaxHoursPerDay = 7,
                            Name = "Project1",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            MaxHoursPerDay = 6,
                            Name = "Project2",
                            Status = 2
                        },
                        new
                        {
                            Id = 3,
                            MaxHoursPerDay = 8,
                            Name = "Project3",
                            Status = 7
                        });
                });

            modelBuilder.Entity("DevelopmentTimer.DAL.Entities.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("DeveloperId")
                        .HasColumnType("int");

                    b.Property<int>("EstimatedHours")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("NotificationThresholdMinutes")
                        .HasColumnType("time");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TotalHours")
                        .HasColumnType("int");

                    b.Property<bool>("isApproved")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DeveloperId");

                    b.HasIndex("ProjectId");

                    b.ToTable("TaskItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateOnly(2025, 9, 17),
                            Description = "Creating the login page with username, password fields, and validation for user authentication.",
                            DeveloperId = 2,
                            EstimatedHours = 2,
                            NotificationThresholdMinutes = new TimeOnly(1, 30, 0),
                            ProjectId = 1,
                            Status = 1,
                            Title = "Login Page",
                            TotalHours = 1,
                            isApproved = false
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateOnly(2025, 9, 14),
                            Description = "Creating the registration page with user input validations, email verification, and password rules.",
                            DeveloperId = 2,
                            EstimatedHours = 3,
                            NotificationThresholdMinutes = new TimeOnly(0, 45, 0),
                            ProjectId = 1,
                            Status = 2,
                            Title = "Register Page",
                            TotalHours = 3,
                            isApproved = true
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateOnly(2025, 9, 16),
                            Description = "Implement login functionality including API integration and proper error handling for Project Beta.",
                            DeveloperId = 3,
                            EstimatedHours = 2,
                            NotificationThresholdMinutes = new TimeOnly(2, 0, 0),
                            ProjectId = 2,
                            Status = 1,
                            Title = "Login Page",
                            TotalHours = 2,
                            isApproved = false
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateOnly(2025, 9, 12),
                            Description = "Implement registration functionality including validations, email service, and security checks for Project Beta.",
                            DeveloperId = 3,
                            EstimatedHours = 3,
                            NotificationThresholdMinutes = new TimeOnly(1, 0, 0),
                            ProjectId = 2,
                            Status = 2,
                            Title = "Register Page",
                            TotalHours = 3,
                            isApproved = true
                        });
                });

            modelBuilder.Entity("DevelopmentTimer.DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "Admin@1234",
                            Role = 0,
                            Username = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Password = "Sita@1234",
                            Role = 1,
                            Username = "Sita"
                        },
                        new
                        {
                            Id = 3,
                            Password = "Rita@5678",
                            Role = 1,
                            Username = "Rita"
                        });
                });

            modelBuilder.Entity("DevelopmentTimer.DAL.Entities.ExtensionsRequest", b =>
                {
                    b.HasOne("DevelopmentTimer.DAL.Entities.User", "Developer")
                        .WithMany("ExtensionRequests")
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DevelopmentTimer.DAL.Entities.TaskItem", "TaskItem")
                        .WithMany("ExtensionRequests")
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Developer");

                    b.Navigation("TaskItem");
                });

            modelBuilder.Entity("DevelopmentTimer.DAL.Entities.TaskItem", b =>
                {
                    b.HasOne("DevelopmentTimer.DAL.Entities.User", "Developer")
                        .WithMany("Tasks")
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DevelopmentTimer.DAL.Entities.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Developer");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("DevelopmentTimer.DAL.Entities.Project", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("DevelopmentTimer.DAL.Entities.TaskItem", b =>
                {
                    b.Navigation("ExtensionRequests");
                });

            modelBuilder.Entity("DevelopmentTimer.DAL.Entities.User", b =>
                {
                    b.Navigation("ExtensionRequests");

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
