// <auto-generated />
using System;
using DevelopmentTimer.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DevelopmentTimer.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DevelopmentTimer.DAL.Entities.ExtensionsRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeveloperId")
                        .HasColumnType("int");

                    b.Property<int>("ExtraHours")
                        .HasColumnType("int");

                    b.Property<string>("Justification")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TaskItemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeveloperId");

                    b.HasIndex("TaskItemId");

                    b.ToTable("ExtensionRequests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeveloperId = 2,
                            ExtraHours = 1,
                            Justification = "To create responsive design",
                            RequestDate = new DateTime(2025, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TaskItemId = 1
                        },
                        new
                        {
                            Id = 2,
                            DeveloperId = 3,
                            ExtraHours = 2,
                            Justification = "To create responsive design",
                            RequestDate = new DateTime(2025, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TaskItemId = 3
                        });
                });

            modelBuilder.Entity("DevelopmentTimer.DAL.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MaxHoursPerDay")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MaxHoursPerDay = 7,
                            Name = "Project1",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            MaxHoursPerDay = 6,
                            Name = "Project2",
                            Status = 2
                        },
                        new
                        {
                            Id = 3,
                            MaxHoursPerDay = 8,
                            Name = "Project3",
                            Status = 7
                        });
                });

            modelBuilder.Entity("DevelopmentTimer.DAL.Entities.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("DeveloperId")
                        .HasColumnType("int");

                    b.Property<int>("EstimatedHours")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("DeveloperId");

                    b.HasIndex("ProjectId");

                    b.ToTable("TaskItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Login Page Creation",
                            DeveloperId = 2,
                            EstimatedHours = 2,
                            ProjectId = 1,
                            Status = 1,
                            Title = "Login Page"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Register Page Creation",
                            DeveloperId = 2,
                            EstimatedHours = 3,
                            ProjectId = 1,
                            Status = 2,
                            Title = "Register Page"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Login Page Creation",
                            DeveloperId = 3,
                            EstimatedHours = 2,
                            ProjectId = 2,
                            Status = 1,
                            Title = "Login Page"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Register Page Creation",
                            DeveloperId = 3,
                            EstimatedHours = 3,
                            ProjectId = 2,
                            Status = 2,
                            Title = "Register Page"
                        });
                });

            modelBuilder.Entity("DevelopmentTimer.DAL.Entities.TimeSheet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("int");

                    b.Property<int>("DeveloperId")
                        .HasColumnType("int");

                    b.Property<decimal>("HoursWorked")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)");

                    b.Property<DateTime?>("SubmissionDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Submitted")
                        .HasColumnType("bit");

                    b.Property<int>("TaskItemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeveloperId");

                    b.HasIndex("TaskItemId");

                    b.ToTable("Timesheets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApprovalStatus = 3,
                            DeveloperId = 2,
                            HoursWorked = 5m,
                            SubmissionDate = new DateTime(2025, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Submitted = true,
                            TaskItemId = 1
                        },
                        new
                        {
                            Id = 2,
                            ApprovalStatus = 7,
                            DeveloperId = 2,
                            HoursWorked = 4m,
                            SubmissionDate = new DateTime(2025, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Submitted = false,
                            TaskItemId = 2
                        });
                });

            modelBuilder.Entity("DevelopmentTimer.DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "Admin@1234",
                            Role = 0,
                            Username = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Password = "Sita@1234",
                            Role = 1,
                            Username = "Sita"
                        },
                        new
                        {
                            Id = 3,
                            Password = "Rita@5678",
                            Role = 1,
                            Username = "Rita"
                        });
                });

            modelBuilder.Entity("DevelopmentTimer.DAL.Entities.ExtensionsRequest", b =>
                {
                    b.HasOne("DevelopmentTimer.DAL.Entities.User", "Developer")
                        .WithMany("ExtensionRequests")
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DevelopmentTimer.DAL.Entities.TaskItem", "TaskItem")
                        .WithMany("ExtensionRequests")
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Developer");

                    b.Navigation("TaskItem");
                });

            modelBuilder.Entity("DevelopmentTimer.DAL.Entities.TaskItem", b =>
                {
                    b.HasOne("DevelopmentTimer.DAL.Entities.User", "Developer")
                        .WithMany("Tasks")
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DevelopmentTimer.DAL.Entities.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Developer");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("DevelopmentTimer.DAL.Entities.TimeSheet", b =>
                {
                    b.HasOne("DevelopmentTimer.DAL.Entities.User", "Developer")
                        .WithMany("Timesheets")
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DevelopmentTimer.DAL.Entities.TaskItem", "TaskItem")
                        .WithMany("Timesheets")
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Developer");

                    b.Navigation("TaskItem");
                });

            modelBuilder.Entity("DevelopmentTimer.DAL.Entities.Project", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("DevelopmentTimer.DAL.Entities.TaskItem", b =>
                {
                    b.Navigation("ExtensionRequests");

                    b.Navigation("Timesheets");
                });

            modelBuilder.Entity("DevelopmentTimer.DAL.Entities.User", b =>
                {
                    b.Navigation("ExtensionRequests");

                    b.Navigation("Tasks");

                    b.Navigation("Timesheets");
                });
#pragma warning restore 612, 618
        }
    }
}
